"""Add missions table

Revision ID: efeca7af2c6e
Revises: e9e3f3fa8325
Create Date: 2026-04-25 16:42:33.140444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efeca7af2c6e'
down_revision: Union[str, Sequence[str], None] = 'e9e3f3fa8325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('task_name', sa.String(length=256), nullable=False),
        sa.Column('location_name', sa.String(length=256), nullable=False),
        sa.Column('description', sa.String(length=1024), nullable=False),
        sa.Column('mission_type', sa.String(length=64), nullable=False),
        sa.Column('estimated_duration_mins', sa.Integer(), nullable=False),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('nearest_station_id', sa.String(length=32), nullable=True),
        sa.Column('nearest_station_name', sa.String(length=64), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    # ### end Alembic commands ###
